# Generated by Django 4.0.6 on 2022-07-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TireStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_code', models.CharField(blank=True, max_length=255, null=True)),
                ('available_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('price_in_usd', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
