# Generated by Django 4.0.6 on 2022-07-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockupdater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirestock',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
