# Generated by Django 4.0.6 on 2022-07-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockupdater', '0002_tirestock_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirestock',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
