# Generated by Django 4.0.6 on 2022-07-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockupdater', '0004_tirestock_available_quantity_by_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_id', models.CharField(max_length=255, unique=True)),
                ('time_started', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('time_completed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
