# Generated by Django 4.0.6 on 2022-07-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockupdater', '0005_scriptlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AveragedTireProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_code', models.CharField(max_length=255, unique=True)),
                ('total_available_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('average_price_in_usd', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
