# Generated by Django 4.0.6 on 2022-07-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockupdater', '0006_averagedtireproductdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagedtireproductdata',
            name='product_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
